export const TOGGLE_MENU = "TOGGLE_MENU";
export const SELECT_PLAY_VIDEO = "SELECT_PLAY_VIDEO";
export const PAGE = "PAGE";
export const TOKEN = "TOKEN";
export const FETCH_USERS_ADDED = "FETCH_USERS_ADDED";
export const FETCH_PARTNERS_ADDED="FETCH_PARTNERS_ADDED"
export const FETCH_GROUPS_ADDED="FETCH_GROUPS_ADDED"
export const FETCH_TEAMS_ADDED="FETCH_TEAMS_ADDED"
export const SELECTED_PARTNER="SELECTED_PARTNER"
export const SELECTED_GROUP="SELECTED_GROUP"
export const SELECTED_TEAM="SELECTED_TEAM"
export const FORMATTED_COURSES="FORMATTED_COURSES"
export const STORE_MENU_ITEMS="STORE_MENU_ITEMS"
export const STORE_SELECTED_DASHBOARD_USER="STORE_SELECTED_DASHBOARD_USER"
export const STORE_DASHBOARD_DATA="STORE_DASHBOARD_DATA"

